[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>", "Philip Craig <philipjcraig@gmail.com>", "Jon Gjengset <jon@thesquareplanet.com>", "Noah Bergbauer <noah.bergbauer@tum.de>"]
description = "A cross-platform symbolication library written in Rust, using `gimli`"
documentation = "https://docs.rs/addr2line"
keywords = ["DWARF", "debug", "elf", "symbolicate", "atos"]
categories = ["development-tools::debugging", "command-line-utilities"]
license = "Apache-2.0/MIT"
name = "addr2line"
readme = "./README.md"
repository = "https://github.com/gimli-rs/addr2line"
version = "0.6.0"
exclude = ["/benches/*", "/fixtures/*"]

[badges]
travis-ci = { repository = "gimli-rs/addr2line" }

[dependencies]
gimli = "0.14"
fallible-iterator = "0.1"
object = "0.7"
intervaltree = "0.2"
smallvec = "0.4"
lazy-init = "0.2"
rustc-demangle = { version = "0.1", optional = true }
cpp_demangle = { version = "0.2", optional = true }

[dev-dependencies]
memmap = "0.6"
clap = "2"
backtrace = "0.3"
findshlibs = "0.3"
rustc-test = "0.2"
unwind = { git = "https://github.com/gimli-rs/unwind-rs.git", rev = "f2f00120f697669867724c943e8082275dc87850" }

[profile.release]
debug = true
[profile.bench]
debug = true

[features]
default = ["rustc-demangle", "cpp_demangle"]

[[test]]
name = "output_equivalence"
harness = false

[[test]]
name = "correctness"

[replace]
"gimli:0.14.0" = { git = 'https://github.com/main--/gimli.git', branch = 'unwind-patches' }

